### ISSUE TITLE
The MPI_Comm_rank() function was called before MPI_INIT was invoked.

### ISSUE THREAD

**Issue by yclai1114** [ShuangLI59/person_search#18]
Hi, I tried to run the training but face the following error. It complaint the MPI_Comm_rank() function was called before MPI_INIT was invoked.

ubuntu@ubuntu-S2600CW:~/Downloads/person_search$ experiments/scripts/train.sh 0 --set EXP_DIR resnet50
+ set -e
+ export PYTHONUNBUFFERED=True
+ PYTHONUNBUFFERED=True
+ GPU_ID=0
+ NET=resnet50
+ DATASET=psdb
+ array=($@)
+ len=4
+ EXTRA_ARGS='--set EXP_DIR resnet50'
+ EXTRA_ARGS_SLUG=--set_EXP_DIR_resnet50
+ case $DATASET in
+ TRAIN_IMDB=psdb_train
+ TEST_IMDB=psdb_test
+ PT_DIR=psdb
+ ITERS=50000
++ date +%Y-%m-%d_%H-%M-%S
+ LOG=experiments/logs/psdb_train_resnet50_--set_EXP_DIR_resnet50.txt.2017-02-28_19-27-37
+ exec
++ tee -a experiments/logs/psdb_train_resnet50_--set_EXP_DIR_resnet50.txt.2017-02-28_19-27-37
+ echo Logging output to experiments/logs/psdb_train_resnet50_--set_EXP_DIR_resnet50.txt.2017-02-28_19-27-37
Logging output to experiments/logs/psdb_train_resnet50_--set_EXP_DIR_resnet50.txt.2017-02-28_19-27-37
+ python2 tools/train_net.py --gpu 0 --solver models/psdb/resnet50/solver.prototxt --weights data/imagenet_models/resnet50.caffemodel --imdb psdb_train --iters 50000 --cfg experiments/cfgs/resnet50.yml --rand --set EXP_DIR resnet50
Called with args:
Namespace(cfg_file='experiments/cfgs/resnet50.yml', gpu='0', imdb_name='psdb_train', max_iters=50000, pretrained_model='data/imagenet_models/resnet50.caffemodel', previous_state=None, randomize=True, set_cfgs=['EXP_DIR', 'resnet50'], solver='models/psdb/resnet50/solver.prototxt')
Using config:
{'DATA_DIR': '/home/ubuntu/Downloads/person_search/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'resnet50',
 'GPU_ID': 0,
 'MATLAB': 'matlab',
 'MODELS_DIR': '/home/ubuntu/Downloads/person_search/models/pascal_voc',
 'PIXEL_MEANS': array([[[ 102.9801,  115.9465,  122.7717]]]),
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/ubuntu/Downloads/person_search',
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': True,
          'MAX_SIZE': 1000,
          'NMS': 0.4,
          'PROPOSAL_METHOD': 'selective_search',
          'RPN_MIN_SIZE': 16,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': True,
           'BATCH_SIZE': 128,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'MAX_SIZE': 1000,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 16,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_INFIX': '',
           'SNAPSHOT_ITERS': 10000,
           'USE_FLIPPED': True,
           'USE_PREFETCH': False},
 'USE_GPU_NMS': True}
*** The MPI_Comm_rank() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.

**Comment by Cysu** [comment]
Did you use `cmake .. -DUSE_MPI=ON`? Also please make sure `mpirun` is in your system path, since cmake will use that to locate the mpi library. The cmake output log should contain lines like
```shell
-- Found MPI_C: /usr/lib64/openmpi/libmpi.so  
-- Found MPI_CXX: /usr/lib64/openmpi/libmpi_cxx.so;/usr/lib64/openmpi/libmpi.so
```

**Comment by yclai1114** [comment]
I found the issue. It was cause by multiple version of protobuf installed in my computer.

**Comment by Cysu** [comment]
Good to hear that!

**Comment by GBJim** [comment]
Hi @Cysu,
I encountered the exact error. 
When I  `cmake .. -DUSE_MPI=ON` 

These lines are missing from my cmake output:
> -- Found MPI_C: /usr/lib64/openmpi/libmpi.so  
> -- Found MPI_CXX: /usr/lib64/openmpi/libmpi_cxx.so;/usr/lib64/openmpi/libmpi.so

How do I solve this?
Since my environment has a 1.65 openMPI installed, I additionally installed 2.0.3 in another path.
I guess I need to manually specify the path of openMPI in cMake. But I am not sure how to do that.

**Comment by Cysu** [comment]
@GBJim, could you please check the output of the following commands?
```bash
which mpirun
mpirun --version
ldd caffe/build/install/bin/caffe | grep mpi
```

**Comment by GBJim** [comment]
Hi @Cysu 
I realized that my openMPI was too new: 2.0.3
The problem is solved after openMPI downgraded to 1.8.8.

Thanks for you help!

**Comment by GerrieWell** [comment]
Hi .I follow your operation and still unable to solve it .Here is my info:

```shell
(py27) wuyong@xy-desktop:~/xy_share/reidPrj/person_search$ /home/wuyong/anaconda3/envs/py27/bin/python tools/demo.py --gpu 0
*** The MPI_Comm_rank() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[xy-desktop:19517] Local abort before MPI_INIT completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!
(py27) wuyong@xy-desktop:~/xy_share/reidPrj/person_search$ mpirun --version
mpirun: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /usr/local/lib/libopen-pal.so.6)
mpirun (Open MPI) 1.8.8

Report bugs to http://www.open-mpi.org/community/help/
(py27) wuyong@xy-desktop:~/xy_share/reidPrj/person_search$ ldd caffe/build/install/bin/caffe | grep mpi
	libmpi.so.1 => /usr/local/lib/libmpi.so.1 (0x00007f0fda767000)
(py27) wuyong@xy-desktop:~/xy_share/reidPrj/person_search$ echo $PATH
/usr/local/cuda-8.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/wuyong/bin
(py27) wuyong@xy-desktop:~/xy_share/reidPrj/person_search$ echo $PYTHONPATH
/home/wuyong/xy_share/reidPrj/person_search/caffe/build/install/python
(py27) wuyong@xy-desktop:~/xy_share/reidPrj/person_search$
```

Can u give me some tips ?what's problem above. And how do u install openmpi 1.8.8 . I just install it to default path (/usr/local/) . And modify relevant variable by ccmake . Finally I get my caffe.But still stunk in `MPI_Comm_rank` .

**Comment by Cysu** [comment]
@GerrieWell `which mpirun`?

**Comment by GerrieWell** [comment]
@Cysu 
which mpirun
/usr/local/bin/mpirun
echo $LD_LIBRARY_PATH
/usr/local/lib/:/usr/local/cuda-8.0/lib64:/usr/local/cuda-8.0/extras/CUPTI/lib64:

btw,I have ever done this for solving some compile problem ,relative to openCL version problem.
 [编译错误求指导 · Issue #146 · yjxiong/caffe](https://github.com/yjxiong/caffe/issues/146 )

**Comment by GerrieWell** [comment]
Can anyone help me to troubleshoot it?
The caffe repository can't be summited an issue.

```
(py27) wuyong@xy-desktop:~/xy_share/reidPrj/person_search$ python -c 'import caffe;caffe.mpi_init()'
*** The MPI_Comm_rank() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[xy-desktop:19155] Local abort before MPI_INIT completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```

**Comment by Cysu** [comment]
I'm not sure, but it seems that `/usr/local/lib/libopen-pal.so.6` should link to some system `libOpenCL.so.1` other than `/usr/local/cuda-8.0/lib64/libOpenCL.so.1`. You may check where the system's `libOpenCL.so.1` is and prepend the directory path before `LD_LIBRARY_PATH`.
